version: '3.7'

services:
  ansible-menagment-node:
    build:
      context: .
      dockerfile: .docker/ansible/Dockerfile
    container_name: ansible-menagment-node
    stdin_open: true
    tty: true
    working_dir: /etc/ansible
    volumes:
      - ./:/etc/ansible/
    networks:
      - ansible

  debian:
    build:
      context: .
      dockerfile: .docker/ansible/Dockerfile
      target: ssh
    container_name: debian
    stdin_open: true
    tty: true
    ports:
      - ${EXTERNAL_SSH_PORT:-22}:22
    networks:
      - ansible

networks:
  ansible:
    name: ansible
