- name: update-apt-cache
  apt: update_cache=yes cache_valid_time=86400
  changed_when: false

- name: restart docker
  service:
    name: docker
    state: "{{ docker_restart_handler_state }}"
  ignore_errors: "{{ ansible_check_mode }}"
  when: docker_service_manage | bool
